plugin:
    name: 'linkonoid.schemamarkup::lang.plugin.name'
    description: 'linkonoid.schemamarkup::lang.plugin.description'
    author: 'Linkonoid'
    icon: 'icon-share-alt'
    iconSvg: 'plugins/linkonoid/schemamarkup/assets/images/schemamarkup-icon.svg'
    homepage: 'https://github.com/linkonoid/oc-schemamarkup'
permissions:
    linkonoid.schemamarkup.access_settings:
        tab: 'linkonoid.schemamarkup::lang.permissions.tab'
        label: 'linkonoid.schemamarkup::lang.permissions.label'
settings:
    settings:
        label: 'linkonoid.schemamarkup::lang.plugin.name'
        description: 'linkonoid.schemamarkup::lang.plugin.description'
        category: 'Linkonoid Frontend Bundle'
        icon: 'icon-share-alt'
        iconSvg: 'plugins/linkonoid/schemamarkup/assets/images/schemamarkup-icon.svg'
        class: 'Linkonoid\SchemaMarkup\Models\Settings'
        order: 500,
        keywords: 'seo schema.org schema-org markup'
        permissions:
            - 'linkonoid.schemamarkup.access_settings'